apiVersion: v1
kind: PersistentVolume
metadata:
  name: db
  namespace: lxc
  labels:
    pv: db
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle 
  storageClassName: nfs 
  nfs:
    path: /data/nfsdata
    server: master

